### PR TITLE
Fix incorrect default icon color for ili for v5

### LINKED ISSUE #183: Incorrect Default Icon color for ILI
The default icon color for InfoListItem in Figma is gray[500]/black[200] (light/dark). Our RN implementation uses theme.colors.text which is black[500]/black[50]. This is a bug and should be logged on the RN components library (make sure to add a note to be careful about the items in the drawer, because they should use different defaults)

The hero defaults to theme.colors.text, which I believe is correct according to the docs (there are actually no examples of Hero in figma with the default color, but I assume matching the text is the expected default). EmptyState should use a different shade of gray, but Huayun has already logged a bug for that.

_Originally posted by @joebochill in https://github.com/pxblue/react-native-showcase-demo/issues/19#issuecomment-893711853_

### PR DESCRIPTION
**Pull request by daileytj**
Fixes #183.

#### Changes proposed in this Pull Request:
- Update default iconColor for InfoListItem

### CODE REVIEW

**Review by jeffvg — APPROVED** [review]

File: components/src/core/info-list-item/info-list-item.tsx [hunk 1]
```diff
@@ -333,7 +333,7 @@ export const InfoListItem: React.FC<InfoListItemProps> = (props) => {
                     : Colors.black[500]
                 : Colors.white[50]; // default avatar is dark gray -> white text
         }
-        return statusColor ? statusColor : theme.colors.text;
+        return statusColor ? statusColor : theme.dark ? Colors.black[200] : Colors.gray[500];
```
Comment (joebochill) [inline components/src/core/info-list-item/info-list-item.tsx:336]: these should be coming from the updated theme properties and will need a fallback in the event that someone is incorrectly using an older theme with newer components, something like:
```suggestion
        return statusColor ? statusColor : (theme.dark ? theme.colors.textPalette.secondary || theme.colors.text);
```

Comment (huayunh) [reply components/src/core/info-list-item/info-list-item.tsx:336]: Let's leave a comment there so that we know what this logic is for

File: CHANGELOG.md [hunk 2]
```diff
@@ -8,6 +8,7 @@
 
 ### Changed
 
+-   Default `iconColor` for `<InfoListItem>` ([#183](https://github.com/pxblue/react-native-component-library/issues/183)).
```
Comment (joebochill) [inline CHANGELOG.md:11]: I would call this a 'Fixed' instead of a 'Changed'

**Review by joebochill — APPROVED** [review]
