### PR TITLE
Add UserMenu and MobileStepper docs and fix headerContent alignment

### LINKED ISSUE #115: Header component's text/icons are not center aligned
#### Describe the bug
The text and icons in the header are not center aligned.

#### What is the expected behavior?
Text and Icons should all be center-aligned in the header.

#### What are the steps to reproduce?
1. Open showcase to view a fully built out `<Header>` example.
2. Observe alignment issues.

#### Screenshots or links to minimum reproduction example
Simulator Screen Shot - iPhone 11 - 2021-02-08 at 06 32 46

Screen Shot 2021-02-08 at 6 39 19 AM

### PR DESCRIPTION
**Pull request by daileytj**
Fixes #115.

#### Changes proposed in this Pull Request:
- Add UserMenu and MobileStepper docs (just throwing this in here because I noticed they aren't on the component doc site... forgot to add them when I built them)
- Fix headerContent alignment (This was the best solution I could come up with. I think there's an issue with the height being set to 64 somewhere instead of 56 but I can't figure out how it's happening, so there's a margin being added when the header is collapsed. I don't love it but it works ¯\_(ツ)_/¯ )

### CODE REVIEW

File: components/src/core/header/headerContent.tsx [hunk 1]
```diff
@@ -215,9 +215,15 @@ export const HeaderContent: React.FC<HeaderContentProps> = (props) => {
     const { headerHeight } = useHeaderHeight();
     const { searching, searchConfig } = useSearch();
     const defaultStyles = headerContentStyles;
+    const [collapsed, setCollapsed] = useState(true);
 
     let content: JSX.Element[] = [];
 
+    useEffect(() => {
+        const listener = headerHeight.addListener(({ value }) => setCollapsed(value === REGULAR_HEIGHT));
+        headerHeight.removeListener(listener);
```
Comment (joebochill) [inline components/src/core/header/headerContent.tsx:224]: my PR eliminates the need for this function entirely, but wanted to point out that you need to return a function in this hook in order to clean up the listener. What you have now destroys the listener immediately (collapsed always stays false).
```suggestion
        return () => headerHeight.removeListener(listener);
```

**Review by joebochill — APPROVED** [review]
